### ISSUE TITLE
Using two mice / 2 player mode in Lemmings 1

### ISSUE THREAD

**Issue by Gagert** [FrodeSolheim/fs-uae#194] opened 2019-03-08 21:57 UTC
This has been my main Amiga emulator for a while mainly because of the xinput support for games which supports a 2 player mode (I had some issues using multiple Xbox One gamepads on WinUAE).

There is however one case I had to give up getting to work properly, and that was using two mouses in Lemmings 1 for multiplayer. I tried writing this and that in the config text file for Lemmings, but even though I managed to get all the other 2 player games working with one Xbox One gamepad for each player, I could not manage to get two mouses to work seperately in the 2 player mode in Lemmings 1.

I suppose fs-uae as of now (fs-uae 2.9.7 dev3) doesn't support 2 player games where mouse is the controller device for both players?

**Comment by FrodeSolheim** [comment] 2019-05-11 11:08
It should work, but it's been a while since I tested it. You are using Windows?

**Comment by FrodeSolheim** [comment] 2019-05-17 18:57
You are right, there was infact a bug, the functionality was accidentally disabled. Is fixed now, will be part of 2.9.9.dev, coming soon :) Thanks for reporting!

**Comment by FrodeSolheim** [comment] 2019-05-17 23:25
Todo: test in WIndows as well

**Comment by Gagert** [comment] 2019-05-19 18:23
Wow; thanks in advance. Can't wait to test it out when the 2.9.9 dev build arrives :)

**Comment by FrodeSolheim** [comment] 2019-05-27 19:31
Actually, it was only fixed for Linux / macOS. There is an additional problem causing it to not work on Windows. I have a theory about what the problem is, and how to fix it.

**Comment by FrodeSolheim** [comment] 2019-05-27 20:10
Theory was correct. Multiple mice seems to work in Windows now :) (Fix will be included in 2.9.11dev).

**Comment by FrodeSolheim** [comment] 2019-05-28 22:28
2.9.11dev is out with fix. Closing this issue.

**Closed by FrodeSolheim** 2019-05-28 22:28 UTC
Labels: bug, confirmed, fixed

**Comment by yukulele** [comment] 2020-04-05 11:34
Hi, 
How to configure FS-UAE to use two mice?
On setting I can only select one mouse, and then both mice move the first cursor.

**Comment by FrodeSolheim** [comment] 2020-04-05 11:36
Depends what operating system you use; you need access to raw mouse devices to see more than one mouse. Have you read the documentation at https://fs-uae.net/docs/mouse ?
