### ISSUE TITLE
vsync breaks fs-uae-launcher

### ISSUE THREAD

**Issue by mistepien** [FrodeSolheim/fs-uae#221] opened 2020-02-02 02:08 UTC
Linux with intel card.
After exit from fullscreen with vsync gui (fs-uae-launcher) is not responsive. But if you switch to console and back then everything is normal again.

**Comment by FrodeSolheim** [comment] 2020-03-11 16:35
Hi, I'm not convinced this is a Launcher issue. It sounds like an issue with the driver / window system or desktop environment

**Comment by FrodeSolheim** [comment] 2021-02-14 09:51
Closing because the issue could not be reproduced, and there isn't enough indication that the problem is with FS-UAE.

**Closed by FrodeSolheim** 2021-02-14 09:51 UTC
Labels: not reproduced
