### ISSUE TITLE
Using serial / parallel port as debug console with FS-UAE?

### ISSUE THREAD

**Issue by cahirwpz** [FrodeSolheim/fs-uae#78] opened 2015-09-21 10:12 UTC
I'd like to use [debug_lib](http://amigadev.elowar.com/read/ADCD_2.1/Includes_and_Autodocs_3._guide/node0123.html) and [ddebug_lib](http://amigadev.elowar.com/read/ADCD_2.1/Includes_and_Autodocs_3._guide/node011A.html) routines to communicate with programs running under emulation. My idea is to use **parallel port** as debugging console (printf debugging) and **serial port** as control console (pause / rewind / change parameters) with my demos.

I'd like FS-UAE to be able to open either **Unix domain socket** or **TCP socket** which I can connect to via minicom or telnet or socat. Is that possible right now? If not would it be possible for you to implement it with not-so-much effort?

**Comment by jens-maus** [comment] 2015-09-22 09:19
I am also highly interested in getting serial debugging working with FS-UAE as I am using it as my debugging system when I don't have my Amiga system at hand.

After some searching on the internet and testing I found the following solution at least for an OS3/m68k UAE session:

(1) Set the following options in your .fs-uae config file:
```
parallel_port = raw:/tmp/vpar
serial_port = /tmp/vser
```
(2) start "socat" with the following command-line options:
```
socat pty,raw,echo=0,link=/tmp/vser -,raw,echo=0
``` 
(3) start your FS-UAE session

This seems to work at least for serial debugging and I am perfectly able to catch all kprintf() output that is usually send to the serial port. However. I haven't managed to get parallel port debugging working, thought.

In addition, the same procedure doesn't seem to work for a OS4/CyberStormPPC session and I am wondering why this doesn't work like it is working for an OS3 FS-UAE session. Perhaps Frode can tell us what needs to be performed to get proper serial debugging on the host that is running the UAE session. Here I really want to use FS-UAE as my main debugging station but for this I have to be able to catch serial debug output output from FS-UAE. Any idea?

**Comment by FrodeSolheim** [comment] 2015-09-22 19:16
As jens-maus said, serial port works already (and you can create a virtual serial port using socat).

As for parallel port, there is no support for that whatsoever in FS-UAE (and no "parallel_port" option either). It is not something I have time to look at right now either (currently being focused on the new x86-64 JIT compilation support).

**Comment by jens-maus** [comment] 2015-09-25 09:22
I just checked WinUAE and there one can set the serial port to a TCP socket (e.g. serial_port = TCP://0.0.0.0:1234) and then one can connect via telnet to that port and all serial output will show up there. Something like that would definitely be required to perform proper debugging of Amiga applications.

**Comment by FrodeSolheim** [comment] 2015-09-25 15:21
Serial TCP may be relatively easy to add, please open a separate issue for that specific request. I'll take a look at it :)

**Comment by FrodeSolheim** [comment] 2015-09-27 19:40
I have implemented (ported) TCP/IP serial port support (available in git repo). It has been tested on Linux and Windows.

Regarding parallel port support, there may be something available...
"Adding a Virtual Parallel Port Protocol in FS-UAE"
http://lallafa.de/blog/2013/05/emulating-plipbox-with-fs-uae/

Perhaps I should mainline this into FS-UAE... :)

**Comment by Rhialto** [comment] 2015-09-27 19:58
I once wrote a networked file system (ParNFS) to use Matt Dillon's parallel port connection device (parnet I think it was called). Should be on Aminet somewhere I expect. That sort of thing could also use this, I expect.
Writing remote file systems with AmigaDOS file system is really easy, since the file system already has a packet interface for all its operations. It just needs a fairly simple (de)serialisation and Bob's your uncle.

**Comment by jens-maus** [comment] 2015-09-28 09:30
@FrodeSolheim:

I just tested the latest master branch but here I received the following error when testing your serial tcp changes on Mac OS X:

```
SERIAL_TCP: listen() failed, 0.0.0.0:1234: 102
SERIAL: Could not open device TCP://0.0.0.0:1234
```

I quickly looked over your code but didn't immediately find a potential reason for that. Any idea?

**Comment by jens-maus** [comment] 2015-09-28 09:44
After some quick testing/tuning I found the following patch to actually get the serial tcp stuff running on Mac OS X:

```
--- a/src/od-fs/parser.cpp
+++ b/src/od-fs/parser.cpp
@@ -384,7 +384,7 @@ static int opentcp (const TCHAR *sername)
                write_log (_T("SERIAL_TCP: GetAddrInfoW() failed, %s:%s: %d\n"), name, port, WSAGetLastError ());
                goto end;
        }
-       serialsocket = socket (socketinfo->ai_family, socketinfo->ai_socktype, socketinfo->ai_protocol);
+       serialsocket = socket (AF_INET, SOCK_STREAM, 0);
        if (serialsocket == INVALID_SOCKET) {
                write_log(_T("SERIAL_TCP: socket() failed, %s:%s: %d\n"), name, port, WSAGetLastError ());
                goto end;
```

In fact, I don't know what you use ai_family/ai_socktype/ai_protocol in the socket() call but according to the getaddrinfo() documentation it seems to be wrong to use ai_family, ai_socktype and ai_protocol straight from the filled socking structure. The documentation of getaddrinfo() states:

```
Specifying hints as NULL is equivalent to setting ai_socktype and ai_protocol to 0; ai_family to AF_UNSPEC; and ai_flags  to (AI_V4MAPPED | AI_ADDRCONFIG).
```

Thus, sock type will be 0 as well as ai_protocol. But my above change definitely sets up the socket into the correct state for listen() to work properly.

**Comment by jens-maus** [comment] 2015-09-28 09:57
Unfortunatley I cannot test this for OS4/ppc as fs-uae master branch currently complains about error loading the qemu-uae plugin?!?

```
MESSAGE: Error loading qemu-uae plugin

WARNING: Error loading qemu-uae plugin

MESSAGE: PPC: Error loading qemu-uae plugin

WARNING: PPC: Error loading qemu-uae plugin
```

However, the standard 2.7.1dev version compiled by you works perfectly.

**Comment by FrodeSolheim** [comment] 2015-09-28 10:33
Hi, and can check this out this evening, but I think you misread the documentation. I interpret "Specifying hints as NULL is equivalent to setting ai_socktype and ai_protocol to 0" as meaning that specifying hints as NULL is the same as setting ai_socktype to 0 *in hints*, had you specified it, and not that ai_socktype will be set to 0 in the result.

My guess is that the problem is the getaddrinfo returns a linked list, and for some reason perhaps the first address isn't usable. The code should probably loop until the socket call succeeds by following the ai_next pointer. See https://developer.apple.com/library/mac/documentation/Darwin/Reference/ManPages/man3/getaddrinfo.3.html for an example.

Regarding QEMU-UAE, I'm guessing that you are building a 64-bit FS-UAE version. The QEMU-UAE plugin is currently only downloadable as a 32-bit version for OS X (64-bit version is coming).

**Comment by jens-maus** [comment] 2015-09-28 14:49
Ah you seem to be right. I will see if I can prepare a pull request for you with changes that are using these kind of for() loops instead.

Regarding QEMU-UAE. You are right, I have compiled FS-UAE for 64bit. Where can I get a QEMU-UAE version for 64bit even if they are not stable? Or how can I compile FS-UAE for 32bit again so that QEMU continues to work?

**Comment by FrodeSolheim** [comment] 2015-09-28 15:03
I just tested and fixed it, so you don't have to. Turns out the OS X chose a SOCK_DGRAM instead of SOCK_STREAM when this wasn't hinted (while Linux and Windows chose SOCK_STREAM). I have added a hint about SOCK_STREAM, and also implemented the loop (probably not neccessary, but).

Compiling the 32-bit version consists of compiling FS-UAE and all dependent libraries with compiler and linker option --arch i386 (so that is veeery boring). I'll see if I can publish a 64-bit QEMU-UAE plugin for OS X soon.

**Comment by jens-maus** [comment] 2015-09-28 15:05
Ok, thanks for the fix. Please push it ASAP. In addition, I hope 'soon' means somewhat today or tomorrow because I would really require that feature for OS4 so that I can continue my debugging sessions for getting a new AmiSSL version out ASAP.

**Comment by jens-maus** [comment] 2015-09-28 15:12
BTW/FYI: I think I found the main reason why on OS X it choose SOCK_DGRAM rather than SOCK_STREAM. See here:

```
$ cat /etc/services  | grep 1234
search-agent    1234/udp    # Infoseek Search Agent
search-agent    1234/tcp    # Infoseek Search Agent
```

Thus, on OS X there is an entry for port 1234 which first points to a UDP datagram service and thus the first thing getaddrinfo() returns is SOCK_DGRAM. On Linux such an entry in /etc/service doesn't exist per default and thus there wasn't that reason. However, using a hint on SOCK_STREAM really is the better approach. However, I also think that it would also be enough and correct to simply change the socket() execution to ```socket (AF_INET, SOCK_STREAM, 0)``` rather than using the output of getaddrinfo() because for the serial tcp stuff you always might want these kind of parameter. However, now that you have the getaddrinfo() stuff fixed with a hints and a proper loop I think everything should be fine as well.

**Comment by FrodeSolheim** [comment] 2015-09-28 15:30
Commit is pushed.

Also: http://fs-uae.net/devel/plugins/qemu-uae/qemu-uae_3.6.0qemu2.2.0fs1_macosx_x86-64.tar.gz (fresh from the press, not even tested).

**Comment by Rhialto** [comment] 2015-09-28 22:46
No, you don't want to use `AF_INET`, because then it never works for IPv6, or any other protocols you might have installed. Remember that getaddrinfo(3) says "When ai_family is set to PF_UNSPEC, it means the caller will accept any protocol family supported by the operating system."

**Comment by jens-maus** [comment] 2015-09-29 07:31
@FrodeSolheim 

Thanks for the commit. I just looked over it, but I feel your for{} loop should not only loop around socket() but until listen() because this is where OS X was complaining. In fact, looking at the examples of getaddrinfo in the OS X manuals one can see that they are actually looping until the listen() call as well.

Regarding the 64-bit qemu version this in fact really doesn't work. Here is the output of the fs-uae log:

```
PPC: uae_ppc_cpu_reboot
PPC: Loading QEmu implementation
PLUGIN: Looking up "qemu-uae"
PLUGIN: Checking "/Users/maus/projekte/fs-uae/./qemu-uae.so"
PLUGIN: Checking "/Users/maus/Documents/FS-UAE/Plugins/qemu-uae.so"
PLUGIN: Checking "/Users/maus/Documents/FS-UAE/Plugins/qemu-ppc/3.6.0qemu2.2.0fs1/macosx_x86-64/qemu-uae.so"
DLOPEN: dlopen(/Users/maus/Documents/FS-UAE/Plugins/qemu-ppc/3.6.0qemu2.2.0fs1/macosx_x86-64/qemu-uae.so, 2): Library not loaded: @rpath/libgthread-2.0.0.dylib
  Referenced from: /Users/maus/Documents/FS-UAE/Plugins/qemu-ppc/3.6.0qemu2.2.0fs1/macosx_x86-64/qemu-uae.so
  Reason: image not found
DLOPEN: Failed to open /Users/maus/Documents/FS-UAE/Plugins/qemu-ppc/3.6.0qemu2.2.0fs1/macosx_x86-64/qemu-uae.so
WARNING: Error loading qemu-uae plugin

WARNING: PPC: Error loading qemu-uae plugin
```

So it seems some dependent library is actually missing.

@Rhialto:

You are right, if you consider IPv6 the better approach is actually using getaddrinfo() under all cases. Thanks for reminding me.

**Comment by jens-maus** [comment] 2015-09-29 07:39
@FrodeSolheim 

Please note the following otool output to debug the shared library situation around qemu-ppc:

```
$:~/projekte/fs-uae$ otool -L /Users/maus/Documents/FS-UAE/Plugins/qemu-ppc/3.6.0qemu2.2.0fs1/macosx_x86-64/qemu-uae.so
/Users/maus/Documents/FS-UAE/Plugins/qemu-ppc/3.6.0qemu2.2.0fs1/macosx_x86-64/qemu-uae.so:
	@rpath/qemu-uae.so (compatibility version 0.0.0, current version 0.0.0)
	/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (compatibility version 150.0.0, current version 1153.18.0)
	/System/Library/Frameworks/IOKit.framework/Versions/A/IOKit (compatibility version 1.0.0, current version 275.0.0)
	@rpath/libz.1.dylib (compatibility version 1.0.0, current version 1.2.8)
	@rpath/libgthread-2.0.0.dylib (compatibility version 4401.0.0, current version 4401.1.0)
	@rpath/libglib-2.0.0.dylib (compatibility version 4401.0.0, current version 4401.1.0)
	@rpath/libintl.8.dylib (compatibility version 10.0.0, current version 10.3.0)
	/System/Library/Frameworks/CoreAudio.framework/Versions/A/CoreAudio (compatibility version 1.0.0, current version 1.0.0)
	/System/Library/Frameworks/Cocoa.framework/Versions/A/Cocoa (compatibility version 1.0.0, current version 21.0.0)
	/usr/lib/libstdc++.6.dylib (compatibility version 7.0.0, current version 104.1.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1213.0.0)
	/System/Library/Frameworks/AppKit.framework/Versions/C/AppKit (compatibility version 45.0.0, current version 1348.17.0)
	/System/Library/Frameworks/ApplicationServices.framework/Versions/A/ApplicationServices (compatibility version 1.0.0, current version 48.0.0)
	/System/Library/Frameworks/Foundation.framework/Versions/C/Foundation (compatibility version 300.0.0, current version 1154.0.0)
	/usr/lib/libobjc.A.dylib (compatibility version 1.0.0, current version 228.0.0)
```

**Comment by FrodeSolheim** [comment] 2015-09-29 16:01
@jens-maus Hmm, yes, because of the @rpath in the plugin, the necessary libraries are not found (unless you are running an FS-UAE app bundle containing those libraries).

I have pushed a new commit to the fs-uae repo to make it easier for you to use a self-compiled fs-uae together with qemu-uae:
- Update the fs-uae repo
- Clone https://github.com/FrodeSolheim/qemu-uae so this repo is placed *parallel* to the fs-uae repo
- Compile qemu-uae (no addional dependencies, and I have pushed a commit fixing 64-bit build with clang):

    cd qemu-uae && ./bootstrap && ./configure && make
- Delete the plugin you have downloaded to avoid confusion

Now, when you run ./fs-uae from the fs-uae repo directory, it should find ../qemu-uae/qemu-uae.so, and since you have compiled it on your machine, there shouldn't be any library issues.

**Comment by jens-maus** [comment] 2015-09-29 16:21
@FrodeSolheim 

Thanks for this patch. In fact, I tested it any now the qemu plugin can be loaded without any issue, as it seems. However, now FS-UAE returns me the following error:

```
MESSAGE: UAE boot ROM cannot be used with PPC native OS
WARNING: UAE boot ROM cannot be used with PPC native OS
```

However, I do use the exact same fs-uae config file as with the official 32bit 2.7.0dev version which works with os4/ppc:

```
[fs-uae]
amiga_model = A4000/OS4
cdrom_image_0 = $BASE/CD-ROMs/ClassicInstallCD-53.68.iso
chip_memory = 2048
hard_drive_0 = OS4PPC.hdf
hard_drive_1 = Work.hdf
kickstart_file = Kick4068.a4000.rom
uae_a2065 = slirp
uaegfx_card = 1
window_height = 1024
window_width = 1280
writable_floppy_images = 1
zorro_iii_memory = 262144
joystick_port_1 = nothing
keyboard_key_kp_enter = action_key_backslash
uae_cachesize = 8192
#console_debugger = 1
#parallel_port = raw:/tmp/vpar
#serial_port = /tmp/vser
serial_port = TCP://0.0.0.0:1234
jit_compiler = 1
uae_compfpu = 1
```

Any idea how to solve that?

**Comment by FrodeSolheim** [comment] 2015-09-29 16:31
Hmm, it should not have worked with the 32-bit version either, remove the uaegfx_card option (you cannot use any UAE expansions when using AmigaOS 4).

**Comment by jens-maus** [comment] 2015-09-29 16:46
@FrodeSolheim 

Thanks, this solved that issue. Now OS4 USE starts and also sets up the serial tcp stuff. and I can connect via telnet to it. I also tested to catch serial debug output via the new serial tcp stuff and it actually works. All I need to do is to setup the kernel debugging stuff using the following command:

```
run >NIL: kdebug "console serial"
```

More Info on setting up serial debugging on OS4 can be found here: http://www.os4coding.net/blog/kas1e/advanced-serial-debugging-guide

So thank you again for helping me to finally get a better debugging method implemented to FS-UAE. This will really help me in getting my Amiga applications debugged. So, I am really looking forward in seeing a new official FS-UAE release with this implemented including a new 64bit qemu. In the end I also verified that qemu working on 64bit OS X. Great work!

**Comment by FrodeSolheim** [comment] 2015-09-29 21:37
@cahirwpz Do you have a working program which you know uses these routines to output stuff on the parallel port? If so, then perhaps I can look at forwarding text from the parallel port through a TCP socket when I'm bored.

(Also, do you know of any documentation of the protocol used to output the text?)

**Comment by cahirwpz** [comment] 2015-09-30 08:18
@FrodeSolheim Firstly, thank you for solving the issue with serial port over TCP.

AFAIK parallel port can be put to use with simple AmigaDOS command like `COPY file.txt TO PAR:`

Parallel device example usage program is available under following link: http://amigadev.elowar.com/read/ADCD_2.1/Devices_Manual_guide/node0160.html

Debugging tools like Enforcer, MuForce, BlowUp, WipeOut can be configured to use parallel port instead of serial port as output device.

**Comment by FrodeSolheim** [comment] 2015-10-01 18:52
Please see the latest git commit for support for parallel "printer" over TCP/IP :)

There's a new parallel_port option, works more or less like the serial_port one, you can for example specify parallel_port=tcp://127.0.0.1:1235/wait to have FS-UAE open a listening socket and wait for a connection before booting.

I have only tested the parallel port by echoing text to PAR: via AmigaOS shell.

I've also merged Lallafa's vpar virtual parallel port, but that's a bit overkill for the use case of just receiving printed text from the parallel port.

**Comment by cahirwpz** [comment] 2015-10-02 05:46
Works well with debug.lib and ddebug.lib. Thanks again for excellent work! :+1:

**Comment by FrodeSolheim** [comment] 2015-10-04 21:07
Great, thanks for confirming that it works :) -Closing this issue now!

**Closed by FrodeSolheim** 2015-10-04 21:07 UTC
Labels: enhancement
